---
name: Deploy Status Page

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
  workflow_dispatch: {}

jobs:
  deploy-status-page:
    name: 'Status Page Deployment on Docker Hosts'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [hau-app01]   # add more docker_host runners here as they join
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy app files
        run: rsync -av --delete app/ "/opt/docker/${RUNNER_NAME}_statuspage/config/"
